# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Session-Ipc
version:      0.03
version_from: lib/Apache/Session/Ipc.pm
installdirs:  site
requires:
    Apache::Session:               0
    IPC::Shareable:                0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
